export type ValidSkills =
  | "Next.js"
  | "React"
  | "React Native"
  | "React.js"
  | "Vue.js"
  | "Redux"
  | "Redux Thunk"
  | "Redux Saga"
  | "GraphQL"
  | "Nest.js"
  | "Express.js"
  | "Node.js"
  | "Python"
  | "Django"
  | "FastAPI"
  | "MongoDB"
  | "PostgreSQL"
  | "MySQL"
  | "Redis"
  | "Typescript"
  | "Javascript"
  | "HTML"
  | "HTML5"
  | "CSS"
  | "CSS3"
  | "Sass"
  | "TailwindCSS"
  | "Material UI"
  | "Ant Design"
  | "Bootstrap"
  | "Socket.io"
  | "Stripe"
  | "JWT"
  | "RBAC"
  | "PHP"
  | "Laravel"
  | "Ratchet"
  | "Google Maps API"
  | "AJAX"
  | "jQuery"
  | "Docker"
  | "Kubernetes"
  | "AWS"
  | "AWS CodePipeline"
  | "ECS"
  | "ECR"
  | "Azure"
  | "Azure Pipelines"
  | "CI/CD"
  | "Git"
  | "Jenkins"
  | "Figma"
  | "Firebase"
  | "Google Auth"
  | "Google Cloud"
  | "Databricks"
  | "Vercel"
  | "Netlify"
  | "Three.js"
  | "WebGL"
  | "TensorFlow"
  | "PyTorch"
  | "Spring Boot"
  | "Storybook"
  | "Webpack"
  | "Prisma"
  | "Supabase"
  | "Jest"
  | "Pytest"
  | "Cypress"
  | "Selenium"
  | "Postman"
  | "Enzyme"
  | "PHPUnit"
  | "JMeter"
  | "HIPAA"
  | "Vuetify"
  | "express.js"
  | "Mongoose";

export type ValidCategory =
  | "Full Stack"
  | "Frontend"
  | "Backend"
  | "UI/UX"
  | "Web Dev"
  | "Mobile Dev"
  | "3D Modeling";

export type ValidExpType = "Personal Project" | "Professional";

export type ValidPages =
  | "home"
  | "skills"
  | "experience"
  | "career"
  | "contact"
  | "resume";
